<?php
$arr_seotitle = array(
'/catalog/oborudovanie-dlya-argonodugovoy-svarki/' =>'Аппараты для аргонодуговой сварки - купить сварочный аппарат аргонодуговой сварки по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/buldozer-liebherr-pr-734-litronic/' =>'Бульдозер Liebherr PR 734 Litronic - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/buldozer-liebherr-pr-764-litronic/' =>'Бульдозер Liebherr PR 764 Litronic  - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/buldozery/' =>'Бульдозеры Liebherr - купить бульдозер по выгодной цене от от Аргус Пайплайн Сервис',
'/catalog/crc-evans-iwm/' =>'Сварочный автомат CRC-Evans IWM - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/denyo-dcw-480esw/' =>'Сварочный агрегат Denyo DCW-480ESW - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/denyo-dlw-400lsw/' =>'Сварочный агрегат Denyo DLW-400LSW - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/ekskavator-kolyesnyy-liebherr-a-900-c-litronic-liebherr-a-904-c-litronic/' =>'Экскаватор колесный Liebherr A 904 C Litronic  - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/ekskavatory-gusenichnye/' =>'Гусеничные экскаваторы от Аргус Пайплайн Сервис, купить гусеничный экскаватор по выгодной стоимости в Москве',
'/catalog/ekskavatory-kolyesnye/' =>'Экскаваторы колёсные - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/golovki-dlya-svarki-provolokoy-sploshnogo-secheniya/' =>'Автоматы для сварки плавящимся электродом - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/induktsionnyy-nagrev/' =>'Установки индукционного нагрева - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/invertec-stt-ii/' =>'Инверторный источник питания Invertec STT II - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/invertec-v270-tp/' =>'Сварочный аргонодуговой инвертор Invertec V270 TP - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/invertec-v350-pro/' =>'Сварочный аппарат Invertec V350-PRO - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/kempomat-2500/' =>'Сварочный полуавтомат KempoMat 2500 - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/lincoln-electric-ranger-305-d-k2279-3/' =>'Сварочный агрегат Lincoln Electric RANGER 305-D - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/lincoln-electric-vantage-400-k2502-3/' =>'Автономный сварочный агрегат Lincoln Electric VANTAGE 400 - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/manzhety/' =>'Манжеты для труб - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/mastertig-ac-dc-3500w/' =>'Аппарат аргонодуговой сварки MasterTig AC/DC 3500W - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/mastertig-lt-250/' =>'Сварочный генератор MasterTig LT 250 - купить сварочные генераторы постоянного тока по выгодным ценам',
'/catalog/nzto-argoheat-130/' =>'Купить НЗТО Argoheat 130 по выгодной стоимости от Аргус Пайплайн Сервис',
'/catalog/oborudovanie-dlya-neftegazovogo-servisa/' =>'Оборудование для нефтегазового сервиса - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/oborudovanie-dlya-plazmennoy-rezki/' =>'Плазменная резка металла: купить аппараты плазменной резки металла от Аргус Пайплайн Сервис, цены на оборудование',
'/catalog/oborudovanie-dlya-poluavtomaticheskoy-svarki/' =>'Сварочный полуавтомат: купить сварочные аппараты по выгодной цене в Москве',
'/catalog/oborudovanie-dlya-ruchnoy-dugovoy-svarki/' =>'Аппараты для ручной дуговой сварки, стоимость оборудования от Аргус Пайплайн Сервис',
'/catalog/palatki/' =>'Палатка сварщика - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/pogruzchiki/' =>'Фронтальные погрузчики Liebherr - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/prisadochnye-prutki-dlya-legirovannykh-staley/' =>'Присадочный пруток для сварки, купить присадочные прутки - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/prisadochnye-prutki-dlya-nerzhaveyushchikh-staley/' =>'Присадочные прутки для нержавеющих сталей - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/prisadochnye-prutki-dlya-svarki-alyuminiya/' =>'Присадочные прутки Tig - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/speedtec-505s/' =>'Автомат сварочный для сварки в защитных газах Speedtec 505S - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/superglaze-tig-4043/' =>'Пруток присадочный Superglaze Tig 4043 - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/svarochnye-agregaty/' =>'Сварочные агрегаты: купить автомат для сварки металла по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/tritool-adaptarc/' =>'Tritool AdaptARC - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/trubnye-zakhvaty-deckhand/' =>'Трубный захват - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/trubogiby/' =>'Трубогиб: купить трубогибы по выгодной стоимости от Аргус Пайплайн Сервис',
'/catalog/trubogiby/dlya-kvadratnyh-trub/' =>'Трубогибы для квадратных труб - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/tsentratory/' =>'Центраторы сварочные - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/universalnye-svarochnye-istochniki/' =>'Промышленные источники бесперебойного питания - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/ustanovka-koltyubingovaya-srednego-klassa-mk20t-20/' =>'Установка колтюбинговая среднего класса МК20Т-20 - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/ustanovka-koltyubingovaya-tyazhelogo-klassa-mk30t/' =>'Установка колтюбинговая тяжелого класса МК30Т - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/ustanovki-koltyubingovye/' =>'Колтюбинговая установка - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/vikhretokovye-defektoskopy/' =>'Вихретоковые дефектоскопы - купить по выгодной цене от Аргус Пайплайн Сервис',
'/catalog/vysokoproizvoditelnye-stanki-dlya-podgotovki-kromok-pfm/' =>'Станки для подготовки кромок труб СПК - купить по выгодной цене от Аргус Пайплайн Сервис'
);

if (isset($arr_seotitle[$_SERVER['REQUEST_URI']]))
    $seotitle = $arr_seotitle[$_SERVER['REQUEST_URI']];

$arr_seoh1 = array(
'/catalog/oborudovanie-dlya-argonodugovoy-svarki/' => 'Аппараты для аргонодуговой сварки',
'/catalog/buldozer-liebherr-pr-734-litronic/' => 'Бульдозер Liebherr PR 734 Litronic',
'/catalog/buldozer-liebherr-pr-764-litronic/' => 'Бульдозер Liebherr PR 764 Litronic',
'/catalog/buldozery/' => 'Бульдозеры Liebherr',
'/catalog/crc-evans-iwm/' => 'Сварочный автомат CRC-Evans IWM',
'/catalog/denyo-dcw-480esw/' => 'Сварочный дизельный генератор Denyo DCW-480ESW',
'/catalog/denyo-dlw-400lsw/' => 'Сварочный дизельный генератор Denyo DLW-400LSW',
'/catalog/ekskavator-kolyesnyy-liebherr-a-900-c-litronic-liebherr-a-904-c-litronic/' => 'Экскаватор колесный Liebherr A 904 C Litronic',
'/catalog/ekskavatory-gusenichnye/' => 'Гусеничные экскаваторы',
'/catalog/ekskavatory-kolyesnye/' => 'Экскаваторы колёсные',
'/catalog/golovki-dlya-svarki-provolokoy-sploshnogo-secheniya/' => 'Автоматы для сварки плавящимся электродом',
'/catalog/induktsionnyy-nagrev/' => 'Установки индукционного нагрева',
'/catalog/invertec-stt-ii/' => 'Инверторный источник питания Invertec STT II',
'/catalog/invertec-v270-tp/' => 'Сварочный аппарат Invertec V270 TP',
'/catalog/invertec-v350-pro/' => 'Сварочный аппарат Invertec V350-PRO',
'/catalog/kempomat-2500/' => 'Сварочный полуавтомат KempoMat 2500',
'/catalog/lincoln-electric-ranger-305-d-k2279-3/' => 'Сварочный агрегат Lincoln Electric RANGER 305-D',
'/catalog/lincoln-electric-vantage-400-k2502-3/' => 'Автономный сварочный агрегат Lincoln Electric VANTAGE 400',
'/catalog/manzhety/' => 'Манжеты для труб',
'/catalog/mastertig-ac-dc-3500w/' => 'Аппарат аргонодуговой сварки MasterTig AC/DC 3500W',
'/catalog/mastertig-lt-250/' => 'Сварочный генератор MasterTig LT 250',
'/catalog/nzto-argoheat-130/' => 'НЗТО Argoheat 130',
'/catalog/oborudovanie-dlya-neftegazovogo-servisa/' => 'Оборудование для нефтегазового сервиса',
'/catalog/oborudovanie-dlya-plazmennoy-rezki/' => 'Аппараты для плазменной резки металла',
'/catalog/oborudovanie-dlya-poluavtomaticheskoy-svarki/' => 'Сварочные полуавтоматы',
'/catalog/oborudovanie-dlya-ruchnoy-dugovoy-svarki/' => 'Аппараты для ручной дуговой сварки',
'/catalog/palatki/' => 'Палатки сварщика',
'/catalog/pogruzchiki/' => 'Фронтальные погрузчики Liebherr',
'/catalog/prisadochnye-prutki-dlya-legirovannykh-staley/' => 'Присадочные прутки для сварки',
'/catalog/prisadochnye-prutki-dlya-nerzhaveyushchikh-staley/' => 'Присадочные прутки для нержавеющих сталей',
'/catalog/prisadochnye-prutki-dlya-svarki-alyuminiya/' => 'Присадочные прутки Tig',
'/catalog/speedtec-505s/' => 'Автомат сварочный Speedtec 505S',
'/catalog/superglaze-tig-4043/' => 'Пруток присадочный Superglaze Tig 4043',
'/catalog/svarochnye-agregaty/' => 'Сварочные агрегаты',
'/catalog/tritool-adaptarc/' => 'Tritool AdaptARC',
'/catalog/trubnye-zakhvaty-deckhand/' => 'Трубные захваты',
'/catalog/trubogiby/' => 'Трубогибы',
'/catalog/trubogiby/dlya-kvadratnyh-trub/' => 'Трубогибы для квадратных труб',
'/catalog/tsentratory/' => 'Центраторы',
'/catalog/universalnye-svarochnye-istochniki/' => 'Промышленные источники бесперебойного питания',
'/catalog/ustanovka-koltyubingovaya-srednego-klassa-mk20t-20/' => 'Установка колтюбинговая среднего класса МК20Т-20',
'/catalog/ustanovka-koltyubingovaya-tyazhelogo-klassa-mk30t/' => 'Установка колтюбинговая тяжелого класса МК30Т',
'/catalog/ustanovki-koltyubingovye/' => 'Колтюбинговые установки',
'/catalog/vikhretokovye-defektoskopy/' => 'Вихретоковые дефектоскопы',
'/catalog/vysokoproizvoditelnye-stanki-dlya-podgotovki-kromok-pfm/' => 'Станки для подготовки кромок труб'
);

if (isset($arr_seoh1[$_SERVER['REQUEST_URI']]))
    $seoh1 = $arr_seoh1[$_SERVER['REQUEST_URI']];

?>